# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: mcr.microsoft.com/powershell:preview

before_script:
    - echo "before!"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
     #installdotnet dependencies
    - apt update
    - apt install wget -y
    - wget https://dot.net/v1/dotnet-install.sh 
    - chmod a+x dotnet-install.sh
    - ./dotnet-install.sh --channel 2.0 
    - rm dotnet-install.sh
    #run publish
    - pwsh-preview -Command "Publish-Module -Path . -NuGetApiKey $psgalleryapikey"

